// <auto-generated />
using System;
using Hbsis.Ambev.Unicesumar.Canteen.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Hbsis.Ambev.Unicesumar.Canteen.Infra.Migrations
{
    [DbContext(typeof(CanteenContext))]
    [Migration("20200219145155_UserMigration")]
    partial class UserMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Hbsis.Ambev.Unicesumar.Canteen.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Hbsis.Ambev.Unicesumar.Canteen.Domain.Orders.OrderProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("Hbsis.Ambev.Unicesumar.Canteen.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("38df74cf-bbf1-4c47-a513-b51192162675"),
                            Description = "Adriática",
                            Price = 6.17m
                        },
                        new
                        {
                            Id = new Guid("f9fa7a55-28ef-4dac-a938-170bc8c8e86e"),
                            Description = "Antarctica",
                            Price = 10.56m
                        },
                        new
                        {
                            Id = new Guid("cb91f1d0-726f-4a84-96d1-419e3fe1582d"),
                            Description = "Beck's",
                            Price = 18.05m
                        },
                        new
                        {
                            Id = new Guid("c292141a-2104-4afc-8431-596e40b0e783"),
                            Description = "Bohemia",
                            Price = 21.03m
                        },
                        new
                        {
                            Id = new Guid("5b682ec6-40dc-4e71-a10f-4a0d9dff6b31"),
                            Description = "Brahma",
                            Price = 2.42m
                        },
                        new
                        {
                            Id = new Guid("bea953df-7d78-4364-b2c8-953d1467aef9"),
                            Description = "Budweiser",
                            Price = 27.28m
                        },
                        new
                        {
                            Id = new Guid("1623b63d-db67-4447-8460-52a840ac6f68"),
                            Description = "Caracu",
                            Price = 5.04m
                        },
                        new
                        {
                            Id = new Guid("fe7edab4-2b64-416a-b020-5bfe8b0790bd"),
                            Description = "Cervejaria Colorado",
                            Price = 4.74m
                        },
                        new
                        {
                            Id = new Guid("6acd2a47-4f54-483e-bda5-6e8845024ef0"),
                            Description = "Corona",
                            Price = 29.7m
                        },
                        new
                        {
                            Id = new Guid("31d1631a-0478-4843-8055-66114c5c79ee"),
                            Description = "Franziskaner",
                            Price = 27.52m
                        },
                        new
                        {
                            Id = new Guid("6f596be2-8b26-48ac-b85d-3a4fb3a647a4"),
                            Description = "Goose Island",
                            Price = 7.94m
                        },
                        new
                        {
                            Id = new Guid("46c6ec94-41e2-4564-a99b-f67e487ae7ff"),
                            Description = "Hertog Jan",
                            Price = 4.43m
                        },
                        new
                        {
                            Id = new Guid("908dfa2f-45b5-480f-82a0-a0ac0eb8c72d"),
                            Description = "Hoegaarden",
                            Price = 24.26m
                        },
                        new
                        {
                            Id = new Guid("3b45bc7d-b6a7-4915-8007-fffee5bc1dd6"),
                            Description = "Leffe",
                            Price = 8.86m
                        },
                        new
                        {
                            Id = new Guid("ad99c2eb-beab-4a2b-85eb-fba15ea45864"),
                            Description = "Legítima",
                            Price = 24.78m
                        },
                        new
                        {
                            Id = new Guid("2c013e77-4d8e-412e-9492-f3c2d0be748b"),
                            Description = "Löwenbräu",
                            Price = 25.85m
                        },
                        new
                        {
                            Id = new Guid("3964bb46-b21a-473e-81c2-8d9e648822fe"),
                            Description = "Magnífica do Maranhão",
                            Price = 16.04m
                        },
                        new
                        {
                            Id = new Guid("c0d623b7-6dc2-47a5-90fe-bb266d338e76"),
                            Description = "Norteña",
                            Price = 8.31m
                        },
                        new
                        {
                            Id = new Guid("2d410954-d770-4d8f-865a-63f26e58c757"),
                            Description = "Nossa",
                            Price = 22.69m
                        },
                        new
                        {
                            Id = new Guid("d0c03fda-1183-4a9e-ba50-abb0dc0e466d"),
                            Description = "Original",
                            Price = 14.97m
                        },
                        new
                        {
                            Id = new Guid("dcb96166-3eff-4d2d-b79f-06315ec3f2be"),
                            Description = "Patagonia",
                            Price = 15.11m
                        },
                        new
                        {
                            Id = new Guid("5ce4210a-a73f-464a-9cef-86df80fa3ea7"),
                            Description = "Polar",
                            Price = 10.06m
                        },
                        new
                        {
                            Id = new Guid("2dd4bedb-b7e7-4f05-9941-66bb2b4b7886"),
                            Description = "Quilmes",
                            Price = 9.35m
                        },
                        new
                        {
                            Id = new Guid("d9470a0f-ee73-41ff-85f6-fd9fc76d4bec"),
                            Description = "Serramalte",
                            Price = 23.09m
                        },
                        new
                        {
                            Id = new Guid("9f52b74d-70ff-42cd-8166-42b4d4227dce"),
                            Description = "Serrana",
                            Price = 2.08m
                        },
                        new
                        {
                            Id = new Guid("da436ba6-0830-4e4f-8037-dc7875df8285"),
                            Description = "Skol",
                            Price = 24.58m
                        },
                        new
                        {
                            Id = new Guid("41ab0c59-04a6-45d6-ac20-ef15e8a10d4e"),
                            Description = "Stella Artois",
                            Price = 27.42m
                        },
                        new
                        {
                            Id = new Guid("8a234d72-6b32-44c2-b7c1-51b5186f0750"),
                            Description = "Três Fidalgas",
                            Price = 3.21m
                        },
                        new
                        {
                            Id = new Guid("147e4c5e-a228-4188-abfc-8f612b1b7096"),
                            Description = "Wäls",
                            Price = 2.89m
                        });
                });

            modelBuilder.Entity("Hbsis.Ambev.Unicesumar.Canteen.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Hbsis.Ambev.Unicesumar.Canteen.Domain.Orders.OrderProduct", b =>
                {
                    b.HasOne("Hbsis.Ambev.Unicesumar.Canteen.Domain.Orders.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hbsis.Ambev.Unicesumar.Canteen.Domain.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
