// <auto-generated />
using System;
using Hbsis.Ambev.Unicesumar.Canteen.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Hbsis.Ambev.Unicesumar.Canteen.Infra.Migrations
{
    [DbContext(typeof(CanteenContext))]
    [Migration("20200219145442_UserData")]
    partial class UserData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Hbsis.Ambev.Unicesumar.Canteen.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Hbsis.Ambev.Unicesumar.Canteen.Domain.Orders.OrderProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("Hbsis.Ambev.Unicesumar.Canteen.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("38df74cf-bbf1-4c47-a513-b51192162675"),
                            Description = "Adriática",
                            Price = 9.55m
                        },
                        new
                        {
                            Id = new Guid("f9fa7a55-28ef-4dac-a938-170bc8c8e86e"),
                            Description = "Antarctica",
                            Price = 11.54m
                        },
                        new
                        {
                            Id = new Guid("cb91f1d0-726f-4a84-96d1-419e3fe1582d"),
                            Description = "Beck's",
                            Price = 4.15m
                        },
                        new
                        {
                            Id = new Guid("c292141a-2104-4afc-8431-596e40b0e783"),
                            Description = "Bohemia",
                            Price = 9.25m
                        },
                        new
                        {
                            Id = new Guid("5b682ec6-40dc-4e71-a10f-4a0d9dff6b31"),
                            Description = "Brahma",
                            Price = 28.6m
                        },
                        new
                        {
                            Id = new Guid("bea953df-7d78-4364-b2c8-953d1467aef9"),
                            Description = "Budweiser",
                            Price = 27.51m
                        },
                        new
                        {
                            Id = new Guid("1623b63d-db67-4447-8460-52a840ac6f68"),
                            Description = "Caracu",
                            Price = 11.98m
                        },
                        new
                        {
                            Id = new Guid("fe7edab4-2b64-416a-b020-5bfe8b0790bd"),
                            Description = "Cervejaria Colorado",
                            Price = 20.24m
                        },
                        new
                        {
                            Id = new Guid("6acd2a47-4f54-483e-bda5-6e8845024ef0"),
                            Description = "Corona",
                            Price = 17.13m
                        },
                        new
                        {
                            Id = new Guid("31d1631a-0478-4843-8055-66114c5c79ee"),
                            Description = "Franziskaner",
                            Price = 10.31m
                        },
                        new
                        {
                            Id = new Guid("6f596be2-8b26-48ac-b85d-3a4fb3a647a4"),
                            Description = "Goose Island",
                            Price = 29.81m
                        },
                        new
                        {
                            Id = new Guid("46c6ec94-41e2-4564-a99b-f67e487ae7ff"),
                            Description = "Hertog Jan",
                            Price = 19.6m
                        },
                        new
                        {
                            Id = new Guid("908dfa2f-45b5-480f-82a0-a0ac0eb8c72d"),
                            Description = "Hoegaarden",
                            Price = 11.48m
                        },
                        new
                        {
                            Id = new Guid("3b45bc7d-b6a7-4915-8007-fffee5bc1dd6"),
                            Description = "Leffe",
                            Price = 27.55m
                        },
                        new
                        {
                            Id = new Guid("ad99c2eb-beab-4a2b-85eb-fba15ea45864"),
                            Description = "Legítima",
                            Price = 9.42m
                        },
                        new
                        {
                            Id = new Guid("2c013e77-4d8e-412e-9492-f3c2d0be748b"),
                            Description = "Löwenbräu",
                            Price = 6.31m
                        },
                        new
                        {
                            Id = new Guid("3964bb46-b21a-473e-81c2-8d9e648822fe"),
                            Description = "Magnífica do Maranhão",
                            Price = 13.54m
                        },
                        new
                        {
                            Id = new Guid("c0d623b7-6dc2-47a5-90fe-bb266d338e76"),
                            Description = "Norteña",
                            Price = 19.39m
                        },
                        new
                        {
                            Id = new Guid("2d410954-d770-4d8f-865a-63f26e58c757"),
                            Description = "Nossa",
                            Price = 22.12m
                        },
                        new
                        {
                            Id = new Guid("d0c03fda-1183-4a9e-ba50-abb0dc0e466d"),
                            Description = "Original",
                            Price = 17.2m
                        },
                        new
                        {
                            Id = new Guid("dcb96166-3eff-4d2d-b79f-06315ec3f2be"),
                            Description = "Patagonia",
                            Price = 6.22m
                        },
                        new
                        {
                            Id = new Guid("5ce4210a-a73f-464a-9cef-86df80fa3ea7"),
                            Description = "Polar",
                            Price = 16.08m
                        },
                        new
                        {
                            Id = new Guid("2dd4bedb-b7e7-4f05-9941-66bb2b4b7886"),
                            Description = "Quilmes",
                            Price = 1.33m
                        },
                        new
                        {
                            Id = new Guid("d9470a0f-ee73-41ff-85f6-fd9fc76d4bec"),
                            Description = "Serramalte",
                            Price = 14.29m
                        },
                        new
                        {
                            Id = new Guid("9f52b74d-70ff-42cd-8166-42b4d4227dce"),
                            Description = "Serrana",
                            Price = 19.44m
                        },
                        new
                        {
                            Id = new Guid("da436ba6-0830-4e4f-8037-dc7875df8285"),
                            Description = "Skol",
                            Price = 3.87m
                        },
                        new
                        {
                            Id = new Guid("41ab0c59-04a6-45d6-ac20-ef15e8a10d4e"),
                            Description = "Stella Artois",
                            Price = 3.91m
                        },
                        new
                        {
                            Id = new Guid("8a234d72-6b32-44c2-b7c1-51b5186f0750"),
                            Description = "Três Fidalgas",
                            Price = 12.47m
                        },
                        new
                        {
                            Id = new Guid("147e4c5e-a228-4188-abfc-8f612b1b7096"),
                            Description = "Wäls",
                            Price = 28.75m
                        });
                });

            modelBuilder.Entity("Hbsis.Ambev.Unicesumar.Canteen.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc915b3a-0d98-451e-99c8-d2988079737f"),
                            Login = "higor",
                            Password = "hbsis",
                            Role = "administrator"
                        },
                        new
                        {
                            Id = new Guid("e7815408-72fa-40e6-b631-ec4fc44e6a6f"),
                            Login = "matheus",
                            Password = "hbsis",
                            Role = "manager"
                        },
                        new
                        {
                            Id = new Guid("0166fcd6-02f6-4a94-a3af-7b15f8a2d33f"),
                            Login = "hugo",
                            Password = "hbsis",
                            Role = "client"
                        });
                });

            modelBuilder.Entity("Hbsis.Ambev.Unicesumar.Canteen.Domain.Orders.OrderProduct", b =>
                {
                    b.HasOne("Hbsis.Ambev.Unicesumar.Canteen.Domain.Orders.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hbsis.Ambev.Unicesumar.Canteen.Domain.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
